### ISSUE TITLE
希望加个quantumult小众规则指定

### ISSUE THREAD

**Issue by zhaozhining** [shigalin/Config#2]
您好，能在quantumult小众规则里帮忙加个新加坡视频网站 toggle 的小众指定么，因为这个网站必须要新加坡IP才能正常观看，有了指定，方便使用。
网站官网：https://www.toggle.sg   万分感谢

**Comment by shigalin** [comment]
不好意思，基本不关注Issues，我想这个问题你应该能解决了~
