### ISSUE TITLE
Rejections 百度贴吧APP 

### ISSUE THREAD

**Issue by maxduke** [shigalin/Config#3]
用完整规则，使用百度贴吧APP，会一直产生大量的REJECT请求，且可能造成respring。

看了下应该是rejection 里面的
^https?:\/\/c\.tieba\.baidu\.com\/\w+\/\w+\/(sync|newRnSync|newlog|mlog) - reject
不知道这个是Quantumult 的问题还是 规则的问题。
同条规则在surge2 没有这个问题。
希望能关注下。多谢。

**Comment by maxduke** [comment]
Quantumult 已经支持 simple response 和 1*1的png了，希望规则能够更新支持，可以解决某些 因拒绝策略导致的频繁重复请求

**Comment by shigalin** [comment]
OK，我先联系作者看看能不能开发rewrite的订阅

**Comment by shigalin** [comment]
作者已更新TF版，升级到最新版后订阅链接阻止（ https://raw.githubusercontent.com/shigalin/Config/master/Quantumult_URL.conf ） 即可
